[package]
name = "mc-classic-js"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.133"
serde = { version = "1.0", features = ["derive"] }
rusqlite = { version = "0.32", features = ["bundled"] }
snap = "1"
